import '../styles/global.css'
import type { Metadata } from 'next'
import { Jost } from 'next/font/google'
import NavBar from '../components/NavBar'

const jost = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={jost.className}>
        <NavBar />
        {children}
      </body>
    </html>
  )
}
